[colors.bright]
black = "0xbcbcbc"
blue = "0xd75f00"
cyan = "0x005faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0x878787"
text = "0xeeeeee"

[colors.normal]
black = "0xeeeeee"
blue = "0x0087af"
cyan = "0x005f87"
green = "0x008700"
magenta = "0x878787"
red = "0xaf0000"
white = "0x444444"
yellow = "0x5f8700"

[colors.primary]
background = "0xeeeeee"
foreground = "0x878787"

[font]
size = 12.5
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 1 }

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 1.0
padding = { x = 8, y = 8 }
dynamic_padding = true

[scrolling]
history = 0

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.25

[env]
TERM = "xterm-256color"
